# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 12:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_Champs', '0002_auto_20171220_1056'),
        ('Vendeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boutique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_bout', models.CharField(max_length=254)),
                ('adresse_bout', models.CharField(max_length=254)),
                ('description_bout', models.TextField(blank=True, null=True)),
                ('pays_bout_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dynamic_Champs.Pays', to_field='nom_pays')),
            ],
        ),
        migrations.AddField(
            model_name='vendeur',
            name='registre_commerce_bout',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boutique',
            name='vendeur_bout_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vendeur.Vendeur'),
        ),
    ]
