# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendeur', '0002_auto_20171220_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='boutique',
            name='logo_bout',
            field=models.ImageField(default=0, upload_to='logo_boutique/'),
            preserve_default=False,
        ),
    ]
