# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendeur', '0003_boutique_logo_bout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='pays_bout_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dynamic_Champs.Pays'),
        ),
    ]
