# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendeur', '0004_auto_20171221_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boutique',
            name='logo_bout',
            field=models.ImageField(blank=True, upload_to='logo_boutique/'),
        ),
    ]
