# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_Champs', '0002_auto_20171220_1056'),
        ('Acheteur', '0003_auto_20171220_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_adr', models.CharField(max_length=10)),
                ('ville_adr', models.CharField(max_length=254)),
                ('code_postale_adr', models.PositiveIntegerField(max_length=5)),
                ('pays_adr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dynamic_Champs.Pays')),
            ],
        ),
        migrations.AlterField(
            model_name='acheteur',
            name='adresse_achet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acheteur.Adresse'),
        ),
    ]
