# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acheteur', '0004_auto_20171220_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acheteur',
            name='adresse_achet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acheteur.Adresse'),
        ),
    ]
