# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Acheteur', '0005_auto_20171220_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_carte_livrai', models.CharField(blank=True, max_length=254)),
                ('type_payement_livrai', models.CharField(choices=[('', 'A Domicile'), ('', 'Par Virement'), ('', 'Carte Bancaire')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='acheteur',
            old_name='adresse_achet',
            new_name='adresse_achet_id',
        ),
        migrations.AddField(
            model_name='livraison',
            name='acheteur_livrai_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acheteur.Acheteur'),
        ),
        migrations.AddField(
            model_name='livraison',
            name='adresse_livrai_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Acheteur.Adresse'),
        ),
    ]
