# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-24 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acheteur', '0006_auto_20171220_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresse',
            name='code_postale_adr',
            field=models.PositiveIntegerField(),
        ),
    ]
