# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 15:23
from __future__ import unicode_literals

import Article.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendeur', '0002_auto_20171220_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_prod', models.CharField(max_length=254)),
                ('ref_prod', models.CharField(max_length=254)),
                ('description_prod', models.TextField(blank=True)),
                ('prix_prod', models.DecimalField(decimal_places=3, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Le prix ne peut pas être négative!!')])),
                ('quantite_stock_prod', models.PositiveIntegerField()),
                ('image_prod', models.ImageField(upload_to=Article.models.produit_directory_path)),
                ('boutique_prod_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Vendeur.Boutique')),
            ],
        ),
    ]
