# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='condition_prod',
            field=models.CharField(choices=[('N', 'Nouveau'), ('O', 'Occasion')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
