# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_produit_condition_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='boutique_prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendeur.Boutique'),
        ),
    ]
