# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 20:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20171220_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix_prod',
            new_name='prix_original_prod',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_solder_prod',
            field=models.DecimalField(decimal_places=3, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Le prix ne peut pas être négative!!')]),
        ),
    ]
