# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 20:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0005_auto_20171220_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prix_solder_prod',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Le prix ne peut pas être négative!!')]),
            preserve_default=False,
        ),
    ]
