# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-20 20:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_auto_20171220_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='prix_solder_prod',
        ),
        migrations.AddField(
            model_name='produit',
            name='pourcentage_solde_prod',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Le pourcentage ne peut pas être négative!!'), django.core.validators.MaxValueValidator(limit_value=99, message='Valeur de pourcentage très élevé')]),
            preserve_default=False,
        ),
    ]
