# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_Champs', '0003_marque'),
        ('Article', '0007_auto_20171220_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='marque_prod_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dynamic_Champs.Marque'),
            preserve_default=False,
        ),
    ]
