# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-22 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_produit_marque_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_vendue_prod',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
