# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-25 18:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_produit_quantite_vendue_prod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification_Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kle_value_spec_prod', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='nbr_avis_prod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='note_avis_prod',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='produit',
            name='pourcentage_solde_prod',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Le pourcentage ne peut pas être négative!!'), django.core.validators.MaxValueValidator(limit_value=99, message='Valeur de pourcentage très élevé')]),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_stock_prod',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_vendue_prod',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specification_produit',
            name='produit_spec_prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Article.Produit'),
        ),
    ]
