# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-29 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_Champs', '0003_marque'),
        ('Article', '0011_auto_20171226_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie_prod_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Dynamic_Champs.Categorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specification_produit',
            name='produit_spec_prod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Article.Produit'),
        ),
    ]
