# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Article', '0008_produit_marque_prod_id'),
        ('Acheteur', '0006_auto_20171220_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acheteur_fav_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acheteur.Acheteur')),
                ('produit_fav_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_prod_panier', models.PositiveIntegerField(default=1)),
                ('acheteur_panier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acheteur.Acheteur')),
                ('produit_panier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Produit')),
            ],
        ),
    ]
