# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Relation_Acheteur_Article', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favori',
            new_name='Produit_Favori',
        ),
        migrations.AlterField(
            model_name='panier',
            name='produit_panier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Produit'),
        ),
        migrations.AlterField(
            model_name='produit_favori',
            name='produit_fav_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Article.Produit'),
        ),
    ]
