# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dynamic_Champs', '0002_auto_20171220_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_marque', models.CharField(error_messages={'unique': 'Une marque avec ce nom existe déjà.'}, max_length=50, unique=True)),
            ],
        ),
    ]
